// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package squads_mpl

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// instruction to increase the authority value tracked in the multisig
// This is optional, as authorities are simply PDAs, however it may be helpful
// to keep track of commonly used authorities in a UI.
// This has no functional impact on the multisig or its functionality, but
// can be used to track commonly used authorities (ie, vault 1, vault 2, etc.)
type AddAuthority struct {

	// [0] = [WRITE, SIGNER] multisig
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAddAuthorityInstructionBuilder creates a new `AddAuthority` instruction builder.
func NewAddAuthorityInstructionBuilder() *AddAuthority {
	nd := &AddAuthority{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 1),
	}
	return nd
}

// SetMultisigAccount sets the "multisig" account.
func (inst *AddAuthority) SetMultisigAccount(multisig ag_solanago.PublicKey) *AddAuthority {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(multisig).WRITE().SIGNER()
	return inst
}

// GetMultisigAccount gets the "multisig" account.
func (inst *AddAuthority) GetMultisigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

func (inst AddAuthority) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AddAuthority,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AddAuthority) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AddAuthority) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Multisig is not set")
		}
	}
	return nil
}

func (inst *AddAuthority) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AddAuthority")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=1]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("multisig", inst.AccountMetaSlice.Get(0)))
					})
				})
		})
}

func (obj AddAuthority) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *AddAuthority) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewAddAuthorityInstruction declares a new AddAuthority instruction with the provided parameters and accounts.
func NewAddAuthorityInstruction(
	// Accounts:
	multisig ag_solanago.PublicKey) *AddAuthority {
	return NewAddAuthorityInstructionBuilder().
		SetMultisigAccount(multisig)
}
