// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package squads_mpl

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Instruction to attach an instruction to a transaction.
// Transactions must be in the "draft" status, and any
// signer (aside from execution payer) specified in an instruction
// must match the authority PDA specified during the transaction creation.
type AddInstruction struct {
	IncomingInstruction *IncomingInstruction

	// [0] = [] multisig
	//
	// [1] = [WRITE] transaction
	//
	// [2] = [WRITE] instruction
	//
	// [3] = [WRITE, SIGNER] creator
	//
	// [4] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAddInstructionInstructionBuilder creates a new `AddInstruction` instruction builder.
func NewAddInstructionInstructionBuilder() *AddInstruction {
	nd := &AddInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 5),
	}
	return nd
}

// SetIncomingInstruction sets the "incomingInstruction" parameter.
func (inst *AddInstruction) SetIncomingInstruction(incomingInstruction IncomingInstruction) *AddInstruction {
	inst.IncomingInstruction = &incomingInstruction
	return inst
}

// SetMultisigAccount sets the "multisig" account.
func (inst *AddInstruction) SetMultisigAccount(multisig ag_solanago.PublicKey) *AddInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(multisig)
	return inst
}

// GetMultisigAccount gets the "multisig" account.
func (inst *AddInstruction) GetMultisigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetTransactionAccount sets the "transaction" account.
func (inst *AddInstruction) SetTransactionAccount(transaction ag_solanago.PublicKey) *AddInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(transaction).WRITE()
	return inst
}

// GetTransactionAccount gets the "transaction" account.
func (inst *AddInstruction) GetTransactionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetInstructionAccount sets the "instruction" account.
func (inst *AddInstruction) SetInstructionAccount(instruction ag_solanago.PublicKey) *AddInstruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(instruction).WRITE()
	return inst
}

// GetInstructionAccount gets the "instruction" account.
func (inst *AddInstruction) GetInstructionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetCreatorAccount sets the "creator" account.
func (inst *AddInstruction) SetCreatorAccount(creator ag_solanago.PublicKey) *AddInstruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(creator).WRITE().SIGNER()
	return inst
}

// GetCreatorAccount gets the "creator" account.
func (inst *AddInstruction) GetCreatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *AddInstruction) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *AddInstruction {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *AddInstruction) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

func (inst AddInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AddInstruction,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AddInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AddInstruction) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.IncomingInstruction == nil {
			return errors.New("IncomingInstruction parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Multisig is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Transaction is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Instruction is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Creator is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *AddInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AddInstruction")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("IncomingInstruction", *inst.IncomingInstruction))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=5]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("     multisig", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("  transaction", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("  instruction", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("      creator", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(4)))
					})
				})
		})
}

func (obj AddInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `IncomingInstruction` param:
	err = encoder.Encode(obj.IncomingInstruction)
	if err != nil {
		return err
	}
	return nil
}
func (obj *AddInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `IncomingInstruction`:
	err = decoder.Decode(&obj.IncomingInstruction)
	if err != nil {
		return err
	}
	return nil
}

// NewAddInstructionInstruction declares a new AddInstruction instruction with the provided parameters and accounts.
func NewAddInstructionInstruction(
	// Parameters:
	incomingInstruction IncomingInstruction,
	// Accounts:
	multisig ag_solanago.PublicKey,
	transaction ag_solanago.PublicKey,
	instruction ag_solanago.PublicKey,
	creator ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *AddInstruction {
	return NewAddInstructionInstructionBuilder().
		SetIncomingInstruction(incomingInstruction).
		SetMultisigAccount(multisig).
		SetTransactionAccount(transaction).
		SetInstructionAccount(instruction).
		SetCreatorAccount(creator).
		SetSystemProgramAccount(systemProgram)
}
