// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package squads_mpl

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// The instruction to change the threshold of the multisig and simultaneously add a member
type AddMemberAndChangeThreshold struct {
	NewMember    *ag_solanago.PublicKey
	NewThreshold *uint16

	// [0] = [WRITE, SIGNER] multisig
	//
	// [1] = [] rent
	//
	// [2] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAddMemberAndChangeThresholdInstructionBuilder creates a new `AddMemberAndChangeThreshold` instruction builder.
func NewAddMemberAndChangeThresholdInstructionBuilder() *AddMemberAndChangeThreshold {
	nd := &AddMemberAndChangeThreshold{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 3),
	}
	return nd
}

// SetNewMember sets the "newMember" parameter.
func (inst *AddMemberAndChangeThreshold) SetNewMember(newMember ag_solanago.PublicKey) *AddMemberAndChangeThreshold {
	inst.NewMember = &newMember
	return inst
}

// SetNewThreshold sets the "newThreshold" parameter.
func (inst *AddMemberAndChangeThreshold) SetNewThreshold(newThreshold uint16) *AddMemberAndChangeThreshold {
	inst.NewThreshold = &newThreshold
	return inst
}

// SetMultisigAccount sets the "multisig" account.
func (inst *AddMemberAndChangeThreshold) SetMultisigAccount(multisig ag_solanago.PublicKey) *AddMemberAndChangeThreshold {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(multisig).WRITE().SIGNER()
	return inst
}

// GetMultisigAccount gets the "multisig" account.
func (inst *AddMemberAndChangeThreshold) GetMultisigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetRentAccount sets the "rent" account.
func (inst *AddMemberAndChangeThreshold) SetRentAccount(rent ag_solanago.PublicKey) *AddMemberAndChangeThreshold {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *AddMemberAndChangeThreshold) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *AddMemberAndChangeThreshold) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *AddMemberAndChangeThreshold {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *AddMemberAndChangeThreshold) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

func (inst AddMemberAndChangeThreshold) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AddMemberAndChangeThreshold,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AddMemberAndChangeThreshold) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AddMemberAndChangeThreshold) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.NewMember == nil {
			return errors.New("NewMember parameter is not set")
		}
		if inst.NewThreshold == nil {
			return errors.New("NewThreshold parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Multisig is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Rent is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *AddMemberAndChangeThreshold) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AddMemberAndChangeThreshold")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("   NewMember", *inst.NewMember))
						paramsBranch.Child(ag_format.Param("NewThreshold", *inst.NewThreshold))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=3]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("     multisig", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("         rent", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(2)))
					})
				})
		})
}

func (obj AddMemberAndChangeThreshold) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `NewMember` param:
	err = encoder.Encode(obj.NewMember)
	if err != nil {
		return err
	}
	// Serialize `NewThreshold` param:
	err = encoder.Encode(obj.NewThreshold)
	if err != nil {
		return err
	}
	return nil
}
func (obj *AddMemberAndChangeThreshold) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `NewMember`:
	err = decoder.Decode(&obj.NewMember)
	if err != nil {
		return err
	}
	// Deserialize `NewThreshold`:
	err = decoder.Decode(&obj.NewThreshold)
	if err != nil {
		return err
	}
	return nil
}

// NewAddMemberAndChangeThresholdInstruction declares a new AddMemberAndChangeThreshold instruction with the provided parameters and accounts.
func NewAddMemberAndChangeThresholdInstruction(
	// Parameters:
	newMember ag_solanago.PublicKey,
	newThreshold uint16,
	// Accounts:
	multisig ag_solanago.PublicKey,
	rent ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *AddMemberAndChangeThreshold {
	return NewAddMemberAndChangeThresholdInstructionBuilder().
		SetNewMember(newMember).
		SetNewThreshold(newThreshold).
		SetMultisigAccount(multisig).
		SetRentAccount(rent).
		SetSystemProgramAccount(systemProgram)
}
