// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package squads_mpl

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Instruction to create a multisig transaction.
// Each transaction is tied to a single authority, and must be specified when
// creating the instruction below. authority 0 is reserved for internal
// instructions, whereas authorities 1 or greater refer to a vault,
// upgrade authority, or other.
type CreateTransaction struct {
	AuthorityIndex *uint32

	// [0] = [WRITE] multisig
	//
	// [1] = [WRITE] transaction
	//
	// [2] = [WRITE, SIGNER] creator
	//
	// [3] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewCreateTransactionInstructionBuilder creates a new `CreateTransaction` instruction builder.
func NewCreateTransactionInstructionBuilder() *CreateTransaction {
	nd := &CreateTransaction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetAuthorityIndex sets the "authorityIndex" parameter.
func (inst *CreateTransaction) SetAuthorityIndex(authorityIndex uint32) *CreateTransaction {
	inst.AuthorityIndex = &authorityIndex
	return inst
}

// SetMultisigAccount sets the "multisig" account.
func (inst *CreateTransaction) SetMultisigAccount(multisig ag_solanago.PublicKey) *CreateTransaction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(multisig).WRITE()
	return inst
}

// GetMultisigAccount gets the "multisig" account.
func (inst *CreateTransaction) GetMultisigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetTransactionAccount sets the "transaction" account.
func (inst *CreateTransaction) SetTransactionAccount(transaction ag_solanago.PublicKey) *CreateTransaction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(transaction).WRITE()
	return inst
}

// GetTransactionAccount gets the "transaction" account.
func (inst *CreateTransaction) GetTransactionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetCreatorAccount sets the "creator" account.
func (inst *CreateTransaction) SetCreatorAccount(creator ag_solanago.PublicKey) *CreateTransaction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(creator).WRITE().SIGNER()
	return inst
}

// GetCreatorAccount gets the "creator" account.
func (inst *CreateTransaction) GetCreatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *CreateTransaction) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *CreateTransaction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *CreateTransaction) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst CreateTransaction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_CreateTransaction,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst CreateTransaction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *CreateTransaction) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.AuthorityIndex == nil {
			return errors.New("AuthorityIndex parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Multisig is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Transaction is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Creator is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *CreateTransaction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("CreateTransaction")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("AuthorityIndex", *inst.AuthorityIndex))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("     multisig", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("  transaction", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("      creator", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj CreateTransaction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `AuthorityIndex` param:
	err = encoder.Encode(obj.AuthorityIndex)
	if err != nil {
		return err
	}
	return nil
}
func (obj *CreateTransaction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `AuthorityIndex`:
	err = decoder.Decode(&obj.AuthorityIndex)
	if err != nil {
		return err
	}
	return nil
}

// NewCreateTransactionInstruction declares a new CreateTransaction instruction with the provided parameters and accounts.
func NewCreateTransactionInstruction(
	// Parameters:
	authorityIndex uint32,
	// Accounts:
	multisig ag_solanago.PublicKey,
	transaction ag_solanago.PublicKey,
	creator ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *CreateTransaction {
	return NewCreateTransactionInstructionBuilder().
		SetAuthorityIndex(authorityIndex).
		SetMultisigAccount(multisig).
		SetTransactionAccount(transaction).
		SetCreatorAccount(creator).
		SetSystemProgramAccount(systemProgram)
}
