// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package squads_mpl

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// The instruction to change the threshold of the multisig and simultaneously remove a member
type RemoveMemberAndChangeThreshold struct {
	OldMember    *ag_solanago.PublicKey
	NewThreshold *uint16

	// [0] = [WRITE, SIGNER] multisig
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewRemoveMemberAndChangeThresholdInstructionBuilder creates a new `RemoveMemberAndChangeThreshold` instruction builder.
func NewRemoveMemberAndChangeThresholdInstructionBuilder() *RemoveMemberAndChangeThreshold {
	nd := &RemoveMemberAndChangeThreshold{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 1),
	}
	return nd
}

// SetOldMember sets the "oldMember" parameter.
func (inst *RemoveMemberAndChangeThreshold) SetOldMember(oldMember ag_solanago.PublicKey) *RemoveMemberAndChangeThreshold {
	inst.OldMember = &oldMember
	return inst
}

// SetNewThreshold sets the "newThreshold" parameter.
func (inst *RemoveMemberAndChangeThreshold) SetNewThreshold(newThreshold uint16) *RemoveMemberAndChangeThreshold {
	inst.NewThreshold = &newThreshold
	return inst
}

// SetMultisigAccount sets the "multisig" account.
func (inst *RemoveMemberAndChangeThreshold) SetMultisigAccount(multisig ag_solanago.PublicKey) *RemoveMemberAndChangeThreshold {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(multisig).WRITE().SIGNER()
	return inst
}

// GetMultisigAccount gets the "multisig" account.
func (inst *RemoveMemberAndChangeThreshold) GetMultisigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

func (inst RemoveMemberAndChangeThreshold) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_RemoveMemberAndChangeThreshold,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst RemoveMemberAndChangeThreshold) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *RemoveMemberAndChangeThreshold) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.OldMember == nil {
			return errors.New("OldMember parameter is not set")
		}
		if inst.NewThreshold == nil {
			return errors.New("NewThreshold parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Multisig is not set")
		}
	}
	return nil
}

func (inst *RemoveMemberAndChangeThreshold) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("RemoveMemberAndChangeThreshold")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("   OldMember", *inst.OldMember))
						paramsBranch.Child(ag_format.Param("NewThreshold", *inst.NewThreshold))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=1]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("multisig", inst.AccountMetaSlice.Get(0)))
					})
				})
		})
}

func (obj RemoveMemberAndChangeThreshold) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `OldMember` param:
	err = encoder.Encode(obj.OldMember)
	if err != nil {
		return err
	}
	// Serialize `NewThreshold` param:
	err = encoder.Encode(obj.NewThreshold)
	if err != nil {
		return err
	}
	return nil
}
func (obj *RemoveMemberAndChangeThreshold) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `OldMember`:
	err = decoder.Decode(&obj.OldMember)
	if err != nil {
		return err
	}
	// Deserialize `NewThreshold`:
	err = decoder.Decode(&obj.NewThreshold)
	if err != nil {
		return err
	}
	return nil
}

// NewRemoveMemberAndChangeThresholdInstruction declares a new RemoveMemberAndChangeThreshold instruction with the provided parameters and accounts.
func NewRemoveMemberAndChangeThresholdInstruction(
	// Parameters:
	oldMember ag_solanago.PublicKey,
	newThreshold uint16,
	// Accounts:
	multisig ag_solanago.PublicKey) *RemoveMemberAndChangeThreshold {
	return NewRemoveMemberAndChangeThresholdInstructionBuilder().
		SetOldMember(oldMember).
		SetNewThreshold(newThreshold).
		SetMultisigAccount(multisig)
}
