name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build
      run: go build -o safe .

    - name: TestCommon
      run: go test -v ./common/...

    - name: TestApps
      run: go test -v ./apps/...

    - name: TestCMPEthereumSign
      run: go test -v ./signer -run TestCMPEthereumSign -count 10

    - name: TestObserver
      run: go test -v ./observer/...

    - name: TestKeeper
      run: go test -v ./keeper/...

    - name: TestSigner
      run: go test -v ./signer/...
